# Generated by Django 5.2.12 on 2026-04-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddypurchase',
            name='farmer',
        ),
        migrations.AddField(
            model_name='paddypurchase',
            name='farmer_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paddypurchase',
            name='farmer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
